.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "CLOCK\-RANDOM\-MANUAL\-CLI" "8" "April 2020" "bootclockrandomization" "bootclockrandomization Manual"
.SH "NAME"
\fBclock\-random\-manual\-cli\fR \- random clock setting
.P
.SH "SYNOPSIS"
\fBclock\-random\-manual\-cli\fR time
.SH "DESCRIPTION"
Sets randomized clock relative to time given by user\.
.SH "EXIT CODES"
0 Success\.
.P
non\-zero Error\.
.SH "EXAMPLES"
\fBecho "Fri Sep 30 22:20:00 UTC 2016" | /usr/bin/clock\-random\-manual\-cli\fR
.SH "WWW"
https://www\.whonix\.org/wiki/Boot_Clock_Randomization
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net)\.
