.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "CLOCK\-RANDOM\-MANUAL\-GUI" "8" "April 2020" "bootclockrandomization" "bootclockrandomization Manual"
.SH "NAME"
\fBclock\-random\-manual\-gui\fR \- random clock setting
.P
.SH "SYNOPSIS"
\fBclock\-random\-manual\-gui\fR
.SH "DESCRIPTION"
Sets randomized clock relative to time given by user\.
.SH "EXIT CODES"
0 Success\.
.P
non\-zero Error\.
.SH "EXAMPLES"
\fB/usr/bin/clock\-random\-manual\-gui\fR
.SH "WWW"
https://www\.whonix\.org/wiki/Boot_Clock_Randomization
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net)\.
