#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

source /usr/share/bootclockrandomization/shared

do_start () {
   if [ -e "$FAIL_FILE" ]; then
      rm -f "$FAIL_FILE"
   fi
   if [ -e "$SUCCESS_FILE" ]; then
      rm -f "$SUCCESS_FILE"
   fi

   delay_plus_or_minus="180"

   get_random_time

   ## Set new time. Syntax: date --set @1396733199.112834496
   date --set "@$NEW_TIME.$NANOSECONDS" > /dev/null

   ## Testing the `date` syntax:
   ## sudo date --set @1396733199.112834496 ; date +%s.%N
   ## Sat Apr  5 21:26:39 UTC 2014
   ## 1396733199.114119019
   ## sudo date --set @1396733199.112834496 ; date +%s.%N
   ## Sat Apr  5 21:26:39 UTC 2014
   ## 1396733199.114122807

   log "Changed time from $OLD_TIME ($OLD_TIME_NANOSECONDS)"
   log "               to $(date) ($(date +%s.%N))."

   touch "$SUCCESS_FILE"
   return 0
}

do_start
