#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

source /usr/share/bootclockrandomization/shared

do_status () {
   if [ -e "$SUCCESS_FILE" ]; then
      log "$NAME $SUCCESS_FILE exists."
      exit 0
   else
      log "$NAME $SUCCESS_FILE does not exist."
      exit 1
   fi
}

do_status
